# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('corporation_name', models.CharField(blank=True, max_length=200)),
                ('extra_info', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
                ('user_created', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.CharField(blank=True, max_length=100)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authority.Country')),
            ],
            options={
                'db_table': 'donor_records',
            },
        ),
    ]
