# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_date_extensions.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isaar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('old_id', models.CharField(blank=True, max_length=20, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=1)),
                ('date_existence_from', django_date_extensions.fields.ApproximateDateField()),
                ('date_existence_to', django_date_extensions.fields.ApproximateDateField(blank=True)),
                ('function', models.TextField(blank=True, null=True)),
                ('general_context', models.TextField(blank=True, null=True)),
                ('legal_status', models.CharField(blank=True, max_length=200, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('mandate', models.TextField(blank=True, null=True)),
                ('internal_structure', models.TextField(blank=True, null=True)),
                ('level_of_detail', models.CharField(default='Minimal', max_length=10)),
                ('status', models.CharField(default='Draft', max_length=10)),
                ('institution_identifier', models.CharField(default='HU OSA', max_length=10)),
                ('source', models.TextField(blank=True, null=True)),
                ('internal_note', models.TextField(blank=True, null=True)),
                ('convention', models.TextField(blank=True, null=True)),
                ('user_created', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.CharField(blank=True, max_length=100)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user_approved', models.CharField(blank=True, max_length=100)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('language', models.ManyToManyField(blank=True, to='authority.Language')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'isaar_records',
            },
        ),
        migrations.CreateModel(
            name='IsaarCorporateBodyIdentifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=200)),
                ('rule', models.CharField(blank=True, max_length=200, null=True)),
                ('isaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isaar.Isaar')),
            ],
            options={
                'db_table': 'isaar_corporate_body_identifiers',
            },
        ),
        migrations.CreateModel(
            name='IsaarOtherName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('isaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isaar.Isaar')),
            ],
            options={
                'db_table': 'isaar_other_names',
            },
        ),
        migrations.CreateModel(
            name='IsaarParallelName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('isaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isaar.Isaar')),
            ],
            options={
                'db_table': 'isaar_parallel_names',
            },
        ),
        migrations.CreateModel(
            name='IsaarPlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=200)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('isaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isaar.Isaar')),
            ],
            options={
                'db_table': 'isaar_places',
            },
        ),
        migrations.CreateModel(
            name='IsaarPlaceQualifier',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('qualifier', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'isaar_place_qualifiers',
            },
        ),
        migrations.CreateModel(
            name='IsaarRelationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'isaar_relationships',
            },
        ),
        migrations.CreateModel(
            name='IsaarStandardizedName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('standard', models.CharField(blank=True, max_length=200, null=True)),
                ('isaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isaar.Isaar')),
            ],
            options={
                'db_table': 'isaar_standardized_names',
            },
        ),
        migrations.AddField(
            model_name='isaarplace',
            name='place_qualifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isaar.IsaarPlaceQualifier'),
        ),
        migrations.AddField(
            model_name='isaarothername',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isaar.IsaarRelationship'),
        ),
        migrations.AlterUniqueTogether(
            name='isaarstandardizedname',
            unique_together=set([('isaar', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='isaarplace',
            unique_together=set([('isaar', 'place')]),
        ),
        migrations.AlterUniqueTogether(
            name='isaarparallelname',
            unique_together=set([('isaar', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='isaarothername',
            unique_together=set([('isaar', 'name')]),
        ),
    ]
