# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archival_unit', '0001_initial'),
        ('controlled_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('container_no', models.IntegerField(default=1)),
                ('container_label', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=50, null=True)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('user_created', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.CharField(blank=True, max_length=100)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('archival_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archival_unit.ArchivalUnit')),
                ('carrier_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlled_list.CarrierType')),
            ],
            options={
                'db_table': 'containers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='container',
            unique_together=set([('archival_unit', 'container_no')]),
        ),
    ]
