# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='barcode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='digital_version_exists',
            field=models.BooleanField(default=False),
        ),
    ]
