# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_auto_20180508_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='barcode',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
