# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_auto_20180509_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='technical_metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
