# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-18 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0004_container_technical_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='technical_metadata',
            new_name='digital_version_technical_metadata',
        ),
        migrations.AddField(
            model_name='container',
            name='digital_version_creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
