# Generated by Django 2.2.2 on 2019-07-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0005_auto_20180918_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='carrier_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlled_list.CarrierType'),
        ),
    ]
