# Generated by Django 4.1.7 on 2023-03-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0009_container_digital_version_research_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='digital_version_research_cloud_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
