# Generated by Django 4.1.7 on 2023-03-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0010_container_digital_version_research_cloud_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='legacy_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
