# Generated by Django 4.1.7 on 2023-04-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0011_alter_container_barcode_alter_container_legacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_no',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='digital_version_exists',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='container',
            name='digital_version_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='container',
            name='digital_version_research_cloud',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
