# Generated by Django 4.1.7 on 2023-07-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0012_alter_container_container_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='internal_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
