language: python

python:
  - "3.6"

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source='.' manage.py test

after_success:
  - coveralls