# Generated by Django 4.1.10 on 2023-11-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('container', '0013_container_internal_note'),
        ('finding_aids', '0017_alter_findingaidsentity_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('available_research_cloud', models.BooleanField(db_index=True, default=False)),
                ('available_online', models.BooleanField(db_index=True, default=False)),
                ('technical_metadata', models.TextField(blank=True, null=True)),
                ('research_cloud_path', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='container.container')),
                ('finding_aids_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finding_aids.findingaidsentity')),
            ],
            options={
                'db_table': 'digital_versions',
            },
        ),
        migrations.CreateModel(
            name='DigitalVersionPhysicalCopy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('storage_unit_label', models.CharField(blank=True, max_length=50, null=True)),
                ('digital_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitization.digitalversion')),
            ],
            options={
                'db_table': 'digital_version_physical_copies',
            },
        ),
    ]
