# Generated by Django 4.1.10 on 2023-11-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0002_digitalversion_filename_digitalversion_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalversion',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
