# Generated by Django 4.1.10 on 2023-12-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0003_digitalversion_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalversion',
            name='digital_collection',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
