# Generated by Django 4.1.13 on 2026-02-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0013_container_internal_note'),
        ('finding_aids', '0024_alter_findingaidsentity_is_template'),
        ('digitization', '0004_digitalversion_digital_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalversion',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digital_versions', to='container.container'),
        ),
        migrations.AlterField(
            model_name='digitalversion',
            name='finding_aids_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digital_versions', to='finding_aids.findingaidsentity'),
        ),
    ]
