# Generated by Django 4.1.13 on 2026-02-12 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0005_alter_digitalversion_container_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalversion',
            options={'ordering': ['level', 'identifier', 'filename']},
        ),
        migrations.AlterModelOptions(
            name='digitalversionphysicalcopy',
            options={'ordering': ['-storage_unit', 'storage_unit_label']},
        ),
        migrations.AlterField(
            model_name='digitalversionphysicalcopy',
            name='digital_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_copies', to='digitization.digitalversion'),
        ),
    ]
