# Generated by Django 4.1.10 on 2024-11-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0004_alter_auditlog_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
    ]
