# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_date_extensions.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controlled_list', '0001_initial'),
        ('archival_unit', '0001_initial'),
        ('authority', '0001_initial'),
        ('isaar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('reference_code', models.CharField(max_length=30)),
                ('description_level', models.CharField(choices=[('F', 'Fonds'), ('SF', 'Subfonds'), ('S', 'Series')], max_length=10)),
                ('year_from', models.IntegerField()),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('accruals', models.BooleanField(default=False)),
                ('access_rights_legacy', models.TextField(blank=True, null=True)),
                ('reproduction_rights_legacy', models.TextField(blank=True, null=True)),
                ('date_predominant', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier_estimated', models.TextField(blank=True, null=True)),
                ('carrier_estimated_original', models.TextField(blank=True, null=True)),
                ('administrative_history', models.TextField(blank=True, null=True)),
                ('administrative_history_original', models.TextField(blank=True, null=True)),
                ('archival_history', models.TextField(blank=True, null=True)),
                ('archival_history_original', models.TextField(blank=True, null=True)),
                ('scope_and_content_abstract', models.TextField(blank=True, null=True)),
                ('scope_and_content_abstract_original', models.TextField(blank=True, null=True)),
                ('scope_and_content_narrative', models.TextField(blank=True, null=True)),
                ('scope_and_content_narrative_original', models.TextField(blank=True, null=True)),
                ('appraisal', models.TextField(blank=True, null=True)),
                ('appraisal_original', models.TextField(blank=True, null=True)),
                ('system_of_arrangement_information', models.TextField(blank=True, null=True)),
                ('system_of_arrangement_information_original', models.TextField(blank=True, null=True)),
                ('embargo', django_date_extensions.fields.ApproximateDateField(blank=True)),
                ('physical_characteristics', models.TextField(blank=True, null=True)),
                ('physical_characteristics_original', models.TextField(blank=True, null=True)),
                ('publication_note', models.TextField(blank=True, null=True)),
                ('publication_note_original', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('note_original', models.TextField(blank=True, null=True)),
                ('internal_note', models.TextField(blank=True, null=True)),
                ('internal_note_original', models.TextField(blank=True, null=True)),
                ('archivists_note', models.TextField(blank=True, null=True)),
                ('archivists_note_original', models.TextField(blank=True, null=True)),
                ('rules_conventions', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('user_published', models.CharField(blank=True, max_length=100)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('user_created', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.CharField(blank=True, max_length=100)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('access_rights', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controlled_list.AccessRight')),
                ('archival_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='archival_unit.ArchivalUnit')),
                ('isaar', models.ManyToManyField(blank=True, to='isaar.Isaar')),
                ('language', models.ManyToManyField(to='authority.Language')),
                ('original_locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controlled_list.Locale')),
                ('reproduction_rights', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controlled_list.ReproductionRight')),
                ('rights_restriction_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controlled_list.RightsRestrictionReason')),
            ],
            options={
                'db_table': 'isad_recrods',
            },
        ),
        migrations.CreateModel(
            name='IsadCarrier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carrier_number', models.IntegerField()),
                ('carrier_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlled_list.CarrierType')),
                ('isad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isad.Isad')),
            ],
            options={
                'db_table': 'isad_carriers',
            },
        ),
        migrations.CreateModel(
            name='IsadCreator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=300)),
                ('isad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isad.Isad')),
            ],
            options={
                'db_table': 'isad_creators',
            },
        ),
        migrations.CreateModel(
            name='IsadExtent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approx', models.BooleanField(default=False)),
                ('extent_number', models.IntegerField()),
                ('extent_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlled_list.ExtentUnit')),
                ('isad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isad.Isad')),
            ],
            options={
                'db_table': 'isad_extents',
            },
        ),
        migrations.CreateModel(
            name='IsadLocationOfCopies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('isad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isad.Isad')),
            ],
            options={
                'db_table': 'isad_location_of_copies',
            },
        ),
        migrations.CreateModel(
            name='IsadLocationOfOriginals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('isad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isad.Isad')),
            ],
            options={
                'db_table': 'isad_location_of_originals',
            },
        ),
        migrations.CreateModel(
            name='IsadRelatedFindingAids',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('isad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isad.Isad')),
            ],
            options={
                'db_table': 'isad_related_finding_aids',
            },
        ),
        migrations.AlterUniqueTogether(
            name='isadextent',
            unique_together=set([('isad', 'extent_unit')]),
        ),
        migrations.AlterUniqueTogether(
            name='isadcarrier',
            unique_together=set([('isad', 'carrier_type')]),
        ),
    ]
