# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='isad',
            name='access_rights_legacy_original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isad',
            name='reproduction_rights_legacy_original',
            field=models.TextField(blank=True, null=True),
        ),
    ]
