# Generated by Django 2.2.2 on 2019-07-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isad', '0003_isad_catalog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isad',
            name='archival_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='archival_unit.ArchivalUnit'),
        ),
    ]
