# Generated by Django 2.2.12 on 2020-04-28 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isad', '0004_auto_20190704_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isad',
            name='archival_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='isad', to='archival_unit.ArchivalUnit'),
        ),
    ]
