# Generated by Django 4.1.3 on 2022-12-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isad', '0004_auto_20200428_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='isad',
            name='catalog_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
