# Generated by Django 4.1.7 on 2023-05-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isaar', '0001_initial'),
        ('isad', '0005_auto_20200428_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isad',
            name='isaar',
        ),
        migrations.AddField(
            model_name='isad',
            name='isaar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='isaar.isaar'),
        ),
    ]
