# Generated by Django 4.1.7 on 2023-06-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isad', '0006_remove_isad_isaar_isad_isaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isad',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
