# Generated by Django 4.1.10 on 2024-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isad', '0009_alter_isad_date_created_alter_isad_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isad',
            name='catalog_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='isad',
            name='reference_code',
            field=models.CharField(db_index=True, max_length=30),
        )
    ]
