# Generated by Django 4.1.13 on 2026-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isad', '0010_alter_isad_catalog_id_alter_isad_reference_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='isad',
            name='ark',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
