# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controlled_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivalUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fonds', models.IntegerField()),
                ('subfonds', models.IntegerField(default=0)),
                ('series', models.IntegerField(default=0)),
                ('sort', models.CharField(blank=True, max_length=12)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('title_full', models.CharField(blank=True, max_length=2000, null=True)),
                ('title_original', models.CharField(blank=True, max_length=500, null=True)),
                ('acronym', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_code', models.CharField(max_length=20)),
                ('reference_code_id', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=2)),
                ('status', models.CharField(default='Final', max_length=10)),
                ('ready_to_publish', models.BooleanField(default=False)),
                ('user_created', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.CharField(blank=True, max_length=100)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('original_locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controlled_list.Locale')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='archival_unit.ArchivalUnit')),
                ('theme', models.ManyToManyField(blank=True, to='controlled_list.ArchivalUnitTheme')),
            ],
            options={
                'ordering': ['fonds', 'subfonds', 'series'],
                'db_table': 'archival_units',
            },
        ),
        migrations.AlterUniqueTogether(
            name='archivalunit',
            unique_together=set([('fonds', 'subfonds', 'series', 'level')]),
        ),
    ]
