# Generated by Django 4.1.7 on 2023-06-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival_unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalunit',
            name='fonds',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='reference_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='series',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='subfonds',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
