# Generated by Django 4.1.7 on 2023-06-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival_unit', '0002_alter_archivalunit_fonds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalunit',
            name='fonds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='reference_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='series',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='subfonds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='archivalunit',
            index=models.Index(fields=['parent'], name='archival_un_parent__0bd3e5_idx'),
        ),
        migrations.AddIndex(
            model_name='archivalunit',
            index=models.Index(fields=['fonds'], name='archival_un_fonds_095bee_idx'),
        ),
        migrations.AddIndex(
            model_name='archivalunit',
            index=models.Index(fields=['subfonds'], name='archival_un_subfond_95402a_idx'),
        ),
        migrations.AddIndex(
            model_name='archivalunit',
            index=models.Index(fields=['series'], name='archival_un_series_e4c58b_idx'),
        ),
        migrations.AddIndex(
            model_name='archivalunit',
            index=models.Index(fields=['fonds', 'subfonds', 'series'], name='fsfs_idx'),
        ),
        migrations.AddIndex(
            model_name='archivalunit',
            index=models.Index(fields=['title'], name='archival_un_title_0c3f74_idx'),
        ),
        migrations.AddIndex(
            model_name='archivalunit',
            index=models.Index(fields=['reference_code'], name='archival_un_referen_870360_idx'),
        ),
    ]
