# Generated by Django 4.1.10 on 2024-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival_unit', '0003_alter_archivalunit_fonds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalunit',
            name='fonds',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='reference_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='reference_code_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='series',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='subfonds',
            field=models.IntegerField(db_index=True, default=0),
        )
    ]
