import re

import requests
from django.conf import settings
from django.core.management import BaseCommand, CommandError
from requests.auth import HTTPBasicAuth

from archival_unit.models import ArchivalUnit
from finding_aids.indexers.finding_aids_new_catalog_indexer import FindingAidsNewCatalogIndexer
from finding_aids.indexers.finding_aids_semantic_indexer import FindingAidsSemanticIndexer
from finding_aids.models import FindingAidsEntity
from isad.indexers.isad_new_catalog_indexer import ISADNewCatalogIndexer
from isad.indexers.isad_semantic_indexer import ISADSemanticIndexer


class EmbeddingClient:
    def __init__(self, base_url, timeout):
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout

    def embed_document(self, text):
        response = requests.post(
            f"{self.base_url}/embed",
            json={
                "text": text,
                "type": "document",
            },
            timeout=self.timeout,
        )
        response.raise_for_status()
        payload = response.json()

        if isinstance(payload, list):
            return payload

        for key in ("embedding", "vector", "semantic_vector"):
            if key in payload:
                return payload[key]

        if payload.get("data"):
            first = payload["data"][0]
            if isinstance(first, dict) and "embedding" in first:
                return first["embedding"]

        raise ValueError("Embedding response did not contain a vector.")


def build_hierarchical_context(title, scope_and_content, max_words=80):
    parts = []

    if title:
        parts.append(title.strip())

    if scope_and_content:
        text = re.sub(r"\s+", " ", scope_and_content).strip()
        sentences = re.split(r"(?<=[.!?])\s+", text)

        selected = []
        word_count = 0

        for sentence in sentences:
            words = sentence.split()

            if word_count + len(words) > max_words:
                break

            selected.append(sentence)
            word_count += len(words)

            if len(selected) >= 2:
                break

        if selected:
            parts.append(" ".join(selected))

    return "\n".join(parts)


class Command(BaseCommand):
    help = (
        "Indexes one fonds/subfonds/series slice into the catalog Solr core "
        "with semantic_vector values generated by the embedding service."
    )

    def add_arguments(self, parser):
        parser.add_argument("--fonds", required=True, type=int, help="Fonds number")
        parser.add_argument("--subfonds", required=True, type=int, help="Subfonds number")
        parser.add_argument("--series", required=True, type=int, help="Series number")
        parser.add_argument(
            "--embedding-base-url",
            default=getattr(settings, "SEMANTIC_EMBEDDING_BASE_URL", "http://localhost:8000"),
            help="Base URL for the embedding service. The command posts to <base>/embed.",
        )
        parser.add_argument(
            "--embedding-timeout",
            default=getattr(settings, "SEMANTIC_EMBEDDING_TIMEOUT", 30),
            type=int,
            help="Embedding request timeout in seconds.",
        )
        parser.add_argument(
            "--solr-url",
            default=getattr(settings, "SEMANTIC_SOLR_URL", "http://localhost:8983/solr/catalog"),
            help="Solr catalog core URL.",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Print generated semantic text without calling embeddings or Solr.",
        )

    def handle(self, *args, **options):
        archival_unit = self._get_archival_unit(options)
        embedding_client = EmbeddingClient(
            base_url=options["embedding_base_url"],
            timeout=options["embedding_timeout"],
        )

        solr_url = options["solr_url"].rstrip("/")
        auth = self._get_solr_auth()

        series_context = self._get_series_context(archival_unit)

        indexed_count = 0
        if hasattr(archival_unit, "isad"):
            indexed_count += self._index_isad(
                archival_unit.isad,
                embedding_client,
                solr_url,
                auth,
                series_context,
                dry_run=options["dry_run"],
            )
        else:
            self.stdout.write(self.style.WARNING("No ISAD(G) record found for archival unit."))

        finding_aids_entities = self._get_finding_aids_entities(archival_unit)
        for finding_aids_entity in finding_aids_entities.iterator():
            indexed_count += self._index_finding_aids_entity(
                finding_aids_entity,
                embedding_client,
                solr_url,
                auth,
                series_context,
                dry_run=options["dry_run"],
            )

        if not options["dry_run"]:
            self._commit(solr_url, auth)

        self.stdout.write(self.style.SUCCESS("Processed %s document(s)." % indexed_count))

    def _get_archival_unit(self, options):
        try:
            return ArchivalUnit.objects.get(
                fonds=options["fonds"],
                subfonds=options["subfonds"],
                series=options["series"],
            )
        except ArchivalUnit.DoesNotExist as exc:
            raise CommandError("No archival unit found for the requested hierarchy.") from exc

    def _get_solr_auth(self):
        username = getattr(settings, "SOLR_USERNAME", None)
        password = getattr(settings, "SOLR_PASSWORD", None)
        if username and password:
            return HTTPBasicAuth(username, password)
        return None

    def _get_series_context(self, archival_unit):
        series_unit = archival_unit if archival_unit.level == "S" else None
        if not series_unit or not hasattr(series_unit, "isad"):
            return ""

        series_isad = series_unit.isad
        scope_and_content = "\n".join(
            filter(
                None,
                [
                    series_isad.scope_and_content_abstract,
                    series_isad.scope_and_content_narrative,
                ],
            )
        )
        return build_hierarchical_context(series_unit.title, scope_and_content)

    def _get_finding_aids_entities(self, archival_unit):
        qs = FindingAidsEntity.objects.filter(archival_unit=archival_unit, is_template=False)
        qs = qs.select_related(
            "archival_unit",
            "container",
            "original_locale",
            "primary_type",
        )
        qs = qs.prefetch_related(
            "subject_person",
            "subject_corporation",
            "subject_heading",
            "subject_keyword",
            "findingaidsentitysubject_set",
        )
        return qs

    def _index_isad(self, isad, embedding_client, solr_url, auth, series_context, dry_run):
        if not isad.published:
            self.stdout.write("Skipping unpublished ISAD(G): %s" % isad.reference_code)
            return 0

        indexer = ISADSemanticIndexer(isad.id)
        indexer.create_solr_document()
        semantic_text = self._build_isad_semantic_text(isad, series_context)

        if dry_run:
            self._print_dry_run(indexer.doc["id"], semantic_text)
        else:
            vector = embedding_client.embed_document(semantic_text)
            print(len(vector))
            indexer.doc["semantic_vector"] = vector
            self._send_to_solr(solr_url, indexer.doc, auth, indexer.doc["id"])

        self.stdout.write("Indexed ISAD(G): %s" % isad.reference_code)
        return 1

    def _index_finding_aids_entity(
        self,
        finding_aids_entity,
        embedding_client,
        solr_url,
        auth,
        series_context,
        dry_run,
    ):
        if not finding_aids_entity.published:
            self.stdout.write("Skipping unpublished FindingAidsEntity: %s" % finding_aids_entity.archival_reference_code)
            return 0

        indexer = FindingAidsSemanticIndexer(finding_aids_entity.id)
        indexer.create_solr_document()
        semantic_text = self._build_finding_aids_semantic_text(finding_aids_entity, series_context)

        if dry_run:
            self._print_dry_run(indexer.doc["id"], semantic_text)
        else:
            vector = embedding_client.embed_document(semantic_text)
            print(len(vector))
            indexer.doc["semantic_vector"] = vector
            self._send_to_solr(solr_url, indexer.doc, auth, indexer.doc["id"])

        self.stdout.write("Indexed FindingAidsEntity: %s" % finding_aids_entity.archival_reference_code)
        return 1

    def _build_isad_semantic_text(self, isad, series_context):
        archival_unit = isad.archival_unit
        return self._build_semantic_text(
            title=isad.title,
            description="\n".join(
                filter(
                    None,
                    [
                        isad.scope_and_content_abstract,
                        isad.scope_and_content_narrative,
                    ],
                )
            ),
            subjects=[],
            series_title=self._get_series_title(archival_unit),
            fonds_title=self._get_fonds_title(archival_unit),
            subfonds_title=self._get_subfonds_title(archival_unit),
            hierarchical_context=series_context,
        )

    def _build_finding_aids_semantic_text(self, finding_aids_entity, series_context):
        archival_unit = finding_aids_entity.archival_unit
        return self._build_semantic_text(
            title=finding_aids_entity.title,
            description=finding_aids_entity.contents_summary,
            subjects=self._get_finding_aids_subjects(finding_aids_entity),
            series_title=self._get_series_title(archival_unit),
            fonds_title=self._get_fonds_title(archival_unit),
            subfonds_title=self._get_subfonds_title(archival_unit),
            hierarchical_context=series_context,
        )

    def _build_semantic_text(
        self,
        title,
        description,
        subjects,
        series_title,
        fonds_title,
        subfonds_title,
        hierarchical_context,
    ):
        return "\n\n".join(
            [
                "TITLE:\n%s" % self._clean_text(title),
                "DESCRIPTION:\n%s" % self._clean_text(description),
                "SUBJECTS:\n%s" % self._clean_text(", ".join(subjects)),
                "SERIES:\n%s" % self._clean_text(series_title),
                "FONDS:\n%s" % self._clean_text(fonds_title),
                "SUBFONDS:\n%s" % self._clean_text(subfonds_title),
                "HIERARCHICAL CONTEXT:\n%s" % self._clean_text(hierarchical_context),
            ]
        )

    def _get_finding_aids_subjects(self, finding_aids_entity):
        subjects = []
        subjects.extend(str(person) for person in finding_aids_entity.subject_person.all())
        subjects.extend(str(corporation) for corporation in finding_aids_entity.subject_corporation.all())
        subjects.extend(str(heading) for heading in finding_aids_entity.subject_heading.all())
        subjects.extend(str(keyword) for keyword in finding_aids_entity.subject_keyword.all())
        subjects.extend(subject.subject for subject in finding_aids_entity.findingaidsentitysubject_set.all())
        return list(dict.fromkeys(filter(None, subjects)))

    def _get_series_title(self, archival_unit):
        if archival_unit.level == "S":
            return archival_unit.title
        return ""

    def _get_fonds_title(self, archival_unit):
        fonds = archival_unit.get_fonds()
        return fonds.title if fonds else ""

    def _get_subfonds_title(self, archival_unit):
        subfonds = archival_unit.get_subfonds()
        return subfonds.title if subfonds else ""

    def _clean_text(self, value):
        if not value:
            return ""
        return re.sub(r"\s+", " ", str(value)).strip()

    def _send_to_solr(self, solr_url, doc, auth, solr_id):
        response = requests.post(
            "%s/update/json/docs/" % solr_url,
            json=doc,
            auth=auth,
            timeout=getattr(settings, "REQUESTS_TIMEOUT", 30),
        )
        if response.status_code >= 400:
            raise CommandError(
                "Solr rejected document %s with HTTP %s:\n%s"
                % (solr_id, response.status_code, response.text)
            )

    def _commit(self, solr_url, auth):
        response = requests.post(
            "%s/update/" % solr_url,
            params={"commit": "true"},
            json={},
            auth=auth,
            timeout=getattr(settings, "REQUESTS_TIMEOUT", 30),
        )
        response.raise_for_status()
        self.stdout.write("Committed Solr changes.")

    def _print_dry_run(self, solr_id, semantic_text):
        self.stdout.write("\n--- %s ---\n%s\n" % (solr_id, semantic_text))
