# Generated by Django 4.1.3 on 2022-12-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival_unit', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allowed_archival_units',
            field=models.ManyToManyField(blank=True, limit_choices_to={'level': 'S'}, to='archival_unit.archivalunit'),
        )
    ]
