# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-06 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0002_auto_20180515_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingaidsentity',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
