# Generated by Django 2.2.2 on 2019-07-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0003_auto_20181206_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingaidsentitydate',
            name='date_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlled_list.DateType'),
        ),
    ]
