# Generated by Django 4.1.7 on 2023-03-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0007_findingaidsentity_digital_version_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaidsentity',
            name='digital_version_creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='findingaidsentity',
            name='digital_version_research_cloud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='findingaidsentity',
            name='digital_version_technical_metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
