# Generated by Django 4.1.7 on 2023-03-24 15:42

from django.db import migrations
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0008_findingaidsentity_digital_version_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingaidsentity',
            name='date_to',
            field=django_date_extensions.fields.ApproximateDateField(blank=True, null=True),
        ),
    ]
