# Generated by Django 4.1.7 on 2023-03-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0009_alter_findingaidsentity_date_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaidsentity',
            name='digital_version_research_cloud_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
