# Generated by Django 4.1.7 on 2023-04-03 11:45

from django.db import migrations
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0011_alter_findingaidsentity_archival_reference_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingaidsentitydate',
            name='date_to',
            field=django_date_extensions.fields.ApproximateDateField(blank=True, null=True),
        ),
    ]
