# Generated by Django 4.1.7 on 2023-06-07 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_list', '0006_nationality'),
        ('finding_aids', '0013_alter_findingaidsentity_digital_version_exists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaidsentity',
            name='access_rights',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controlled_list.accessright'),
        ),
        migrations.AddField(
            model_name='findingaidsentity',
            name='access_rights_restriction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='findingaidsentity',
            name='access_rights_restriction_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
