# Generated by Django 4.1.7 on 2023-06-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_list', '0007_identifiertype'),
        ('finding_aids', '0015_alter_findingaidsentity_access_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingAidsEntityIdentifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('fa_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finding_aids.findingaidsentity')),
                ('identifier_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlled_list.identifiertype')),
            ],
            options={
                'db_table': 'finding_aids_identifiers',
            },
        ),
    ]
