# Generated by Django 4.1.7 on 2023-07-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0016_findingaidsentityidentifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingaidsentity',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='findingaidsentity',
            name='date_published',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='findingaidsentity',
            name='date_updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
