# Generated by Django 4.1.10 on 2024-01-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0018_alter_findingaidsentity_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingaidsentity',
            name='physical_condition',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
