# Generated by Django 4.1.10 on 2024-10-24 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0020_alter_findingaidsentity_catalog_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingAidsRelatedMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(blank=True, max_length=300, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_destinations', to='finding_aids.findingaidsentity')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_sources', to='finding_aids.findingaidsentity')),
            ],
            options={
                'db_table': 'finding_aids_related_materials',
                'unique_together': {('id', 'source', 'destination')},
            },
        ),
    ]
