# Generated by Django 4.1.10 on 2024-10-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0022_rename_relationship_findingaidsrelatedmaterial_relationship_destination_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FindingAidsRelatedMaterial',
            new_name='FindingAidsEntityRelatedMaterial',
        ),
    ]
