# Generated by Django 4.1.10 on 2025-01-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0023_rename_findingaidsrelatedmaterial_findingaidsentityrelatedmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingaidsentity',
            name='is_template',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
