# Generated by Django 4.1.13 on 2026-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0024_alter_findingaidsentity_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaidsentity',
            name='ark',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
