# Generated by Django 4.1.13 on 2026-07-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0026_findingaidsentity_missing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingaidsentity',
            name='missing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='findingaidsentity',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
