# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['statement'],
                'db_table': 'controlled_rights_access',
            },
        ),
        migrations.CreateModel(
            name='ArchivalUnitTheme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['theme'],
                'db_table': 'controlled_archival_unit_themes',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['building'],
                'db_table': 'controlled_building',
            },
        ),
        migrations.CreateModel(
            name='CarrierType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, unique=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('old_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['type'],
                'db_table': 'controlled_carrier_types',
            },
        ),
        migrations.CreateModel(
            name='CorporationRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100, unique=True)),
                ('user_created', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.CharField(blank=True, max_length=100)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['role'],
                'db_table': 'controlled_corporation_roles',
            },
        ),
        migrations.CreateModel(
            name='DateType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['type'],
                'db_table': 'controlled_date_types',
            },
        ),
        migrations.CreateModel(
            name='ExtentUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['unit'],
                'db_table': 'controlled_extent_units',
            },
        ),
        migrations.CreateModel(
            name='GeoRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100, unique=True)),
                ('user_created', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.CharField(blank=True, max_length=100)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['role'],
                'db_table': 'controlled_geo_roles',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('user_created', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.CharField(blank=True, max_length=100)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['keyword'],
                'db_table': 'controlled_keywords',
            },
        ),
        migrations.CreateModel(
            name='LanguageUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usage', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['usage'],
                'db_table': 'controlled_language_usages',
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('locale_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['locale_name'],
                'db_table': 'controlled_locales',
            },
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100, unique=True)),
                ('user_created', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.CharField(blank=True, max_length=100)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['role'],
                'db_table': 'controlled_person_roles',
            },
        ),
        migrations.CreateModel(
            name='PrimaryType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['type'],
                'db_table': 'controlled_primary_types',
            },
        ),
        migrations.CreateModel(
            name='ReproductionRight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['statement'],
                'db_table': 'controlled_rights_reproduction',
            },
        ),
        migrations.CreateModel(
            name='RightsRestrictionReason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['reason'],
                'db_table': 'controlled_rights_restriction_reason',
            },
        ),
    ]
