# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-10 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_list', '0002_carriertype_type_original_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
