# Generated by Django 4.1.3 on 2022-12-07 13:00

import clockwork_api.mixins.detect_protected_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_list', '0005_alter_keyword_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nationality', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'controlled_nationalities',
                'ordering': ['nationality'],
            },
            bases=(models.Model, clockwork_api.mixins.detect_protected_mixin.DetectProtectedMixin),
        ),
    ]
