# Generated by Django 4.1.7 on 2023-06-16 10:46

import clockwork_api.mixins.detect_protected_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_list', '0006_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, unique=True)),
                ('user_created', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.CharField(blank=True, max_length=100)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'controlled_identifier_types',
                'ordering': ['type'],
            },
            bases=(models.Model, clockwork_api.mixins.detect_protected_mixin.DetectProtectedMixin),
        ),
    ]
