# Generated by Django 3.2.4 on 2021-10-13 08:11

from django.db import migrations
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='creation_date_from',
            field=django_date_extensions.fields.ApproximateDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='creation_date_to',
            field=django_date_extensions.fields.ApproximateDateField(blank=True, null=True),
        ),
    ]
