# Generated by Django 4.1.7 on 2023-03-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0002_auto_20211013_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='module',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='row',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='section',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='shelf',
            field=models.IntegerField(null=True),
        ),
    ]
