# Generated by Django 4.1.3 on 2022-12-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_researcher_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherDegree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'research_degree',
            },
        ),
        migrations.AlterUniqueTogether(
            name='researcher',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
