# Generated by Django 4.1.3 on 2022-12-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_researcherdegree_alter_researcher_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherdegree',
            name='degree',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
