# Generated by Django 4.1.3 on 2022-12-08 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_list', '0006_nationality'),
        ('authority', '0001_initial'),
        ('research', '0004_alter_researcherdegree_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='is_student',
        ),
        migrations.AddField(
            model_name='researcher',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researcher',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='research.researcherdegree'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='employer_or_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='occpuation_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('staff', 'Staff'), ('faculty', 'Faculty')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='occupation',
            field=models.CharField(choices=[('ceu', 'CEU'), ('other', 'Other')], default='ceu', max_length=20),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='citizenship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlled_list.nationality'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authority.country'),
        ),
    ]
