# Generated by Django 4.1.3 on 2022-12-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_remove_researcher_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='token',
        ),
        migrations.AlterField(
            model_name='researcher',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='research_subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
