# Generated by Django 4.1.3 on 2023-01-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_remove_researcher_token_alter_researcher_card_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='occpuation_type',
            new_name='occupation_type',
        ),
    ]
