# Generated by Django 4.1.3 on 2023-01-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_remove_request_finishing_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestItems',
            new_name='RequestItem',
        ),
    ]
