# Generated by Django 4.1.3 on 2023-01-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_rename_requestitems_requestitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
