# Generated by Django 4.1.3 on 2023-01-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_alter_requestitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='archival_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='archival_reference_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
