# Generated by Django 4.1.3 on 2023-01-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_remove_requestitem_finding_aids_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('1', 'In Queue'), ('2', 'Pending'), ('3', 'Processed and prepared'), ('4', 'Reshelved')], default='1', max_length=1),
        ),
    ]
