# Generated by Django 4.1.3 on 2023-01-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_alter_requestitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('1', 'In Queue'), ('2', 'Pending'), ('3', 'Processed and prepared'), ('4', 'Returned'), ('5', 'Reshelved')], default='1', max_length=1),
        ),
    ]
