# Generated by Django 4.1.3 on 2023-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0018_remove_requestitem_archival_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('1', 'In Queue'), ('2', 'Pending'), ('3', 'Processed and prepared'), ('4', 'Returned'), ('5', 'Reshelved'), ('9', 'Uploaded')], default='1', max_length=1),
        ),
    ]
