# Generated by Django 4.1.3 on 2023-02-08 15:36

import clockwork_api.fields.email_null_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0023_alter_researcher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='email',
            field=clockwork_api.fields.email_null_field.EmailNullField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
