# Generated by Django 4.1.7 on 2023-05-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0026_requestitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='ordering',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
