# Generated by Django 4.1.7 on 2023-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0027_requestitem_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='how_do_you_know_osa',
            field=models.CharField(blank=True, choices=[('web', 'OSA Web page'), ('event', 'Event at OSA'), ('verzio', 'Verzio'), ('ceu', 'CEU'), ('contacts', 'Personal Contacts'), ('media', 'Media'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='how_do_you_know_osa_other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
