# Generated by Django 4.1.10 on 2023-10-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0029_alter_requestitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('1', 'In Queue'), ('2', 'Pending'), ('3', 'Processed and prepared'), ('4', 'Returned'), ('5', 'Reshelved'), ('9', 'Uploaded')], default='1', max_length=1),
        ),
    ]
