# Generated by Django 4.1.10 on 2023-11-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0030_alter_requestitem_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='hcaptcha',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
