# Generated by Django 4.1.10 on 2024-01-29 13:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0033_requestitem_restricted_uuid_requestitempart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitem',
            name='restricted_uuid',
        ),
        migrations.CreateModel(
            name='RequestItemRestriction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('restricted_uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('research_organisation', models.TextField()),
                ('research_subject', models.TextField()),
                ('motivation', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('request_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='research.requestitem')),
            ],
            options={
                'db_table': 'research_request_items_restrictions',
            },
        ),
    ]
