# Generated by Django 4.1.10 on 2024-01-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0034_remove_requestitem_restricted_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitemrestriction',
            name='conditions_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestitemrestriction',
            name='motivation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requestitemrestriction',
            name='research_organisation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requestitemrestriction',
            name='research_subject',
            field=models.TextField(blank=True),
        ),
    ]
