# Generated by Django 4.1.10 on 2024-09-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0020_alter_findingaidsentity_catalog_id_and_more'),
        ('research', '0035_requestitemrestriction_conditions_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitempart',
            name='finding_aids_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finding_aids.findingaidsentity'),
        ),
    ]
