# Generated by Django 4.1.10 on 2024-11-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0036_alter_requestitempart_finding_aids_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='library_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
