# Generated by Django 4.1.10 on 2025-01-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0037_requestitem_library_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitemrestriction',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='requestitemrestriction',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='requestitemrestriction',
            name='approved_date',
        ),
        migrations.AddField(
            model_name='requestitempart',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestitempart',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='requestitempart',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
