# Generated by Django 4.1.10 on 2025-09-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0040_alter_requestitempart_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.request'),
        ),
    ]
