# Generated by Django 4.1.10 on 2025-09-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0041_alter_requestitem_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitempart',
            name='request_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.requestitem'),
        ),
    ]
