# Generated by Django 4.1.13 on 2026-02-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0042_alter_requestitempart_request_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherdegree',
            name='show_in_registration_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='occupation',
            field=models.CharField(choices=[('ceu', 'CEU'), ('other', 'Other'), ('ceu_student', 'CEU Student'), ('ceu_faculty', 'CEU Faculty')], default='ceu', max_length=20),
        ),
    ]
