# Generated by Django 4.1.13 on 2026-02-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0043_researcherdegree_show_in_registration_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
