# Generated by Django 4.1.13 on 2026-02-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0044_researcher_house_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='id_number',
        ),
    ]
