# Generated by Django 4.1.13 on 2026-02-26 15:11

from django.db import migrations, models


def set_researcher_status(apps, schema_editor):
    Researcher = apps.get_model('research', 'Researcher')

    for researcher in Researcher.objects.all():
        # Adjust logic based on your description
        if getattr(researcher, "approved", False) and getattr(researcher, "active", False):
            researcher.status = "new"
        if getattr(researcher, "approved", True) and getattr(researcher, "active", True):
            researcher.status = "approved"
        if getattr(researcher, "approved", True) and getattr(researcher, "active", False):
            researcher.status = "suspended"

        researcher.save(update_fields=["status"])


def reverse_set_researcher_status(apps, schema_editor):
    # Optional: reset back to default
    Researcher = apps.get_model('research', 'Researcher')
    Researcher.objects.all().update(status="new")


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0045_remove_researcher_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='new', max_length=10, null=True),
        ),
        migrations.RunPython(set_researcher_status, reverse_set_researcher_status),
    ]
