# Generated by Django 4.1.7 on 2023-03-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personotherformat',
            unique_together={('last_name', 'first_name', 'person')},
        ),
    ]
