# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-25 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_auto_20201019_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationotherformat',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='corporationotherformat',
            unique_together={('corporation', 'name')},
        ),
    ]