# Generated by Django 4.1.10 on 2025-11-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0005_alter_corporation_authority_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_name_folded',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
