# Generated by Django 4.1.10 on 2025-11-12 11:17
import unicodedata

from django.db import migrations

def populate_folded_names(apps, schema_editor):
    Person = apps.get_model("authority", "Person")
    for p in Person.objects.all().iterator():
        p.last_name_folded = (
            unicodedata.normalize('NFKD', p.last_name or '')
            .encode('ascii', 'ignore')
            .decode('ascii')
            .lower()
            .strip()
        )
        p.save(update_fields=["last_name_folded"])


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0006_person_last_name_folded'),
    ]

    operations = [migrations.RunPython(populate_folded_names)]
