# Generated by Django 4.1.10 on 2025-11-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0007_auto_20251112_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='last_name_folded',
        ),
        migrations.AddField(
            model_name='person',
            name='full_name_folded',
            field=models.CharField(blank=True, db_index=True, default='', max_length=210),
        ),
        migrations.AddField(
            model_name='person',
            name='simhash64',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
