# Generated by Django 4.1.10 on 2025-11-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0008_remove_person_last_name_folded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='simhash64',
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
    ]
