# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controlled_list', '0001_initial'),
        ('archival_unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLREntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carrier_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlled_list.CarrierType')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archival_unit.ArchivalUnit')),
            ],
            options={
                'db_table': 'mlr_records',
            },
        ),
        migrations.CreateModel(
            name='MLREntityLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.IntegerField(blank=True, null=True)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('section', models.IntegerField(blank=True, null=True)),
                ('shelf', models.IntegerField(blank=True, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controlled_list.Building')),
                ('mlr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='mlr.MLREntity')),
            ],
            options={
                'db_table': 'mlr_record_locations',
            },
        ),
    ]
