# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlrentity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
