# Generated by Django 3.2.4 on 2021-10-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_list', '0005_alter_keyword_keyword'),
        ('mlr', '0002_mlrentity_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlrentity',
            name='carrier_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlled_list.carriertype'),
        ),
    ]
